 
version: "3"
services:
  frontend:
    build:
       context: ./service-2
    container_name: frontend
    depends_on:
      - backend
    environment: 
      - BACKEND_URL=http://backend/reverse
    ports: 
      - 8081:80
  backend:
    build:
      context: ./service-1
    container_name: backend
    ports: 
      - 8080:80
