# apiVersion: v1
# kind: Pod
# metadata:
#   name: backend
#   labels:
#     app: backend
# spec:
#   containers:
#   - name: backend
#     image: thestrider/service-1
#     resources:
#       limits:
#         memory: "28Mi"
#         cpu: "50m"
#     ports:
#       - containerPort: 80

# ---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        image: thestrider/service-1
        resources:
          limits:
            memory: "28Mi"
            cpu: "50m"
        ports:
          - containerPort: 80


---

# apiVersion: v1
# kind: Service
# metadata:
#   name:  backend-v1
# spec:
#   selector:
#     app:  backend
#   type: NodePort
#   ports:
#   - name:  http
#     port:  8080
#     targetPort: 80