apiVersion: v1
kind: Service
metadata:
  name:  frontend
spec:
  selector:
    app:  frontend
  type: NodePort
  ports:
  - name:  http
    port:  8081 #inside the cluster exposed port
    targetPort: 80 #pods exposes service
    protocol: TCP
  